### PR TITLE
[gULAAkri] apoc.periodic.repeat doesn't always work

### LINKED ISSUE #17: The apoc.periodic.repeat and apoc.periodic.sumbit procedures don't work with some statements which return something
<a href="https://github.com/vga91"></img></a> **Issue by [vga91](https://github.com/vga91)**
_Thursday May 26, 2022 at 14:07 GMT_
_Originally opened as https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/2942_

----

See also: https://community.neo4j.com/t/apoc-periodic-repeat-with-node-similarity/55782/2

## How to Reproduce the Problem

Create 2 similar jobs with the `apoc.log.info` procedure. The 1st return void:
```
CALL apoc.periodic.repeat('jobOne', "CALL apoc.log.info('testOne')", 2)
```
and the 2nd return `1`:
```
CALL apoc.periodic.repeat('jobTwo', "CALL apoc.log.info('testTwo') RETURN 1", 2)
```

Note that only `jobOne` create `log.info`s

-----

The same bug regarding the `apoc.periodic.submit`, for example:
```
CALL apoc.periodic.submit('submit-2', 'CALL apoc.log.info('testThree') RETURN 1', {})
```

---

### Versions

  - OS: MacOs
  - Neo4j: 4.4.5
  - Neo4j-Apoc: 4.4.0.5

### PR DESCRIPTION
**Pull request by vga91**
Fixes #17

Most likely the bug occurs when there is a `RETURN ...` preceded by a void procedure with mode = "READ" (like the related gh issue)

- Added `Result::resultAsString` in order to consume results with void procedures.
- Check that the `db.prepareForReplanning` (which is a void read procedure) logs correctly

### CODE REVIEW

**Review by ncordon — APPROVED** [review]

File: core/src/test/java/apoc/periodic/PeriodicTest.java [hunk 1]
```diff
@@ -51,21 +53,64 @@
...
+        logProvider.clear();
+
+        // execute a periodic procedure with `CALL db.prepareForReplanning` as an inner procedure
+        db.executeTransactionally(query);
+
+        // print logs in logProvider
+        // and check that the previous `prepareForReplanning` logs a "Manual trigger for sampling all indexes"
+        assertEventually(() -> {
+            logProvider.print(System.out);
+            return logProvider.serialize().contains("Manual trigger for sampling all indexes");
```
Comment (ncordon) [inline core/src/test/java/apoc/periodic/PeriodicTest.java:109]: We are relying on something we write to the logs here in a procedure we don't control. We just need a void procedure with some effect right? 

I feel like it would be a better approach if we do a `dbms.setConfigValue` for example, fetching the value of that config afterwards.

**Review by ncordon — APPROVED** [review]
Good job
